apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: warehouse
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: bgd-dev
        overlay: bgd-dev
      - namespace: bgd-prod
        overlay: bgd-prod
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: default
      source:
        path: 'apps/bgd/overlays/{{overlay}}'
        repoURL: https://github.com/adrien-legros/openshift-gitops-examples
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=false
        automated:
          selfHeal: true
          prune: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: bgd-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: bgd-prod
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops