apiVersion: v1
kind: Namespace
metadata:
  name: quarkus-app-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: quarkus-app-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: quarkus
    repoURL: https://github.com/adrien-legros/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false

