apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: alegros-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/helm
    repoURL: https://github.com/adrien-legros/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true