apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd
  namespace: openshift-gitops
spec:
  generators:
  - git:
      directories:
        - path: apps/kustomize/overlays/*
      repoURL: 'https://github.com/adrien-legros/openshift-gitops-examples'
      revision: main
  template:
    metadata:
      name: 'bgd-{{path.basename}}'
    spec:
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/adrien-legros/openshift-gitops-examples
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: 'alegros-bgd-{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true